### ISSUE TITLE
Folder as collapse indicator bug ON IPAD

### ISSUE THREAD

**Issue by dannuen** [primary-theme/obsidian#223]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

V2.8.0

### Debug Info

SYSTEM INFO:
	Operating system: ios 17.5.1 (Apple iPad8,1)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.7
	Login status: not logged in
	Live preview: on
	Base theme: light
	Community theme: Primary v2.8.0
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 38
	Plugins enabled: 34
		1: Calendar v1.5.10
		2: Admonition v10.3.2
		3: Advanced Tables v0.21.0
		4: Bible Linker v1.5.5
		5: Book Search v0.7.4
		6: Contextual Typography v2.2.5
		7: Dataview v0.5.67
		8: Hotkeys++ v0.2.7
		9: Outliner v4.8.1
		10: QuickAdd v1.11.0
		11: Regex Find/Replace v1.2.0
		12: Settings Search v1.3.10
		13: Underline v1.3.0
		14: Trim Whitespace v0.3.0
		15: Text Format v3.1.0
		16: Templater v2.4.1
		17: Style Settings v1.0.8
		18: Omnivore v1.10.4
		19: Linter v1.25.0
		20: Meta Bind v1.1.3
		21: Banners v1.3.3
		22: Homepage v4.0.3
		23: Tag Wrangler v0.6.1
		24: Minimal Theme Settings v8.0.2
		25: Force note view mode v1.2.2
		26: Tasks v7.6.1
		27: Periodic Notes v0.0.17
		28: Typewriter Scroll v0.2.2
		29: Zoom v1.1.2
		30: Natural Language Dates v0.6.2
		31: List Callouts v1.2.7
		32: Checklist v2.2.13
		33: Bulk Rename v0.5.2
		34: Smart Typography v1.0.18

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

Hi, loving the new update!

There is an issue with the folder icons as collapse indicators.

<img width="118" alt="Screenshot 2024-07-29 at 18 18 40 jpeg" src="https://github.com/user-attachments/assets/4d4c4676-6815-42ea-ac6d-aecd98b28552">

**Comment by ceciliamay** [comment]
fixed in upcoming 2.9.0 release!

**Comment by dannuen** [comment]
The problem is still exist in v2.9.0
![Screenshot 2024-09-19 at 15 22 16](https://github.com/user-attachments/assets/b2ff7c81-74cc-4867-8ad9-dd6aaccb771d)

**Comment by ceciliamay** [comment]
please update to the latest 2.9.1! thanks for coming back and reporting on this! i really appreciate it 🙏
